In [29]:
import numpy as np
import pandas as pd

np.random.seed(42)

n = 200      # sample size
J = 10       # number of predictors
rho = 0.5    # correlation structure

In [30]:
Sigma = np.zeros((J,J))

for l in range(J):
    for m in range(J):
        Sigma[l,m] = rho ** abs(l-m)

In [31]:
X = np.random.multivariate_normal(
    mean=np.zeros(J),
    cov=Sigma,
    size=n
)

In [32]:
beta = np.array([
    1.0,
    0.8,
    0.6,
    0.4,
    0.2,
    0,
    0,
    0,
    0,
    0
])

In [33]:
# 先不加截距項
# beta0 = 1

mu = (
    X @ beta
    +0.95 * X[:,0]*X[:,1]
    -0.9 * X[:,2]*X[:,3]
)

# 設定 signal-to-noise ratio，避免interaction被noise蓋過去
SNR = 5


sigma = np.sqrt(
    np.var(mu) / SNR
)


epsilon = np.random.normal(
    0,
    sigma,
    size=n
)

Y = mu + epsilon

In [34]:
data = pd.DataFrame(
    X,
    columns=[f"X{i+1}" for i in range(J)]
)

data["Y"] = Y

data.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,Y
0,-0.364024,-0.535005,-0.098756,0.634783,-0.303584,-1.684369,-0.316628,-0.397418,0.064438,1.116941,-1.215799
1,-0.040984,1.106908,-0.423174,-0.176540,-0.832848,0.405820,0.970306,1.840893,0.497021,-1.324867,0.072064
2,-0.517496,0.186867,-1.212555,-1.701548,-1.329932,-0.644563,-0.353699,-0.172036,-0.483800,-1.312699,-4.928827
3,2.341058,0.980138,0.519837,1.179557,0.385181,0.601411,-0.023183,-1.195339,-0.012944,-1.595165,5.249396
4,-0.716628,0.243905,-0.449510,0.036578,-0.797859,-0.697470,-0.836787,0.909102,-0.850277,-1.019553,-3.328708

In [35]:
data.iloc[:,:10].corr()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10
X1,1.000000,0.552504,0.202136,0.117077,0.133745,0.020668,-0.138343,-0.183516,-0.110144,-0.138742
X2,0.552504,1.000000,0.446186,0.168624,0.143224,0.079221,-0.128632,-0.168842,-0.133458,-0.210097
X3,0.202136,0.446186,1.000000,0.492364,0.298456,0.120196,-0.059434,-0.147561,-0.079633,-0.035390
X4,0.117077,0.168624,0.492364,1.000000,0.512903,0.232847,0.020229,-0.022273,-0.133754,-0.120628
X5,0.133745,0.143224,0.298456,0.512903,1.000000,0.539019,0.237985,0.072977,-0.043454,-0.019118
X6,0.020668,0.079221,0.120196,0.232847,0.539019,1.000000,0.455575,0.189754,-0.020316,-0.015391
X7,-0.138343,-0.128632,-0.059434,0.020229,0.237985,0.455575,1.000000,0.512946,0.190920,0.168609
X8,-0.183516,-0.168842,-0.147561,-0.022273,0.072977,0.189754,0.512946,1.000000,0.505856,0.263228
X9,-0.110144,-0.133458,-0.079633,-0.133754,-0.043454,-0.020316,0.190920,0.505856,1.000000,0.517435
X10,-0.138742,-0.210097,-0.035390,-0.120628,-0.019118,-0.015391,0.168609,0.263228,0.517435,1.000000

In [40]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(
    fit_intercept=False
)

model.fit(
    X,
    Y
)

print(model.intercept_)
print(model.coef_[0:5])

0.0
[0.94375513 0.72839054 0.63686668 0.60903831 0.48635303]